export { default as HeartIcon } from '@assets/icons/heart.svg'
export { default as EyeIcon } from '@assets/icons/eye.svg'
export { default as EyeSlashIcon } from '@assets/icons/eye-slash.svg'
export { default as ChevronLeftIcon } from '@assets/icons/chevron-left.svg'
export { default as InvestlyIcon } from '@assets/icons/investly.svg'