name: Build Android Staging

on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build Android Binary Dev
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Make gradlew executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android Staging
        run: npm run build-android:staging

      - name: Install Firebase
        run: npm install -g firebase-tools

      - name: Distribute app via Firebase App Distribution
        run: 
          firebase appdistribution:distribute android/app/build/outputs/apk/release/app-release.apk \
            --app 1:245729866216:android:06c64c3949c2061d62f45d \
            --groups "QA" \
            --token "${{ secrets.FIREBASE_TOKEN }}"
